<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Depalletizer" Id="{20c004ff-8016-4b71-ac39-37f47934d231}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Depalletizer
VAR_INPUT
	i_xEmergencyButton 		: BOOL;
	i_xStartButton 			: BOOL;
	i_xStopButton 			: BOOL;
END_VAR
VAR_OUTPUT
	o_eState : eSingleState;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>