<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Klep" Id="{8f632325-bc23-4204-82f5-b4ed35cd42af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Klep
VAR_INPUT
	i_eState 			: eSingleState;
	i_xWantedPosition 	: BOOL;
	i_xHallSensorIn		: BOOL;
	i_xHallSensorOut 	: BOOL;
END_VAR
VAR_OUTPUT
	o_xCurrentPosition 		: BOOL;
	o_xMagnetValve			: BOOL;
	o_xWarningMagnetValve 	: BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>