<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Klep" Id="{8f632325-bc23-4204-82f5-b4ed35cd42af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Klep
VAR_INPUT
	i_eState 			: eSingleState;
	i_eWantedPosition 	: eValvePosition;
	i_xHallSensorIn		: BOOL;
	i_xHallSensorOut 	: BOOL;
	i_xWarningReset		: BOOL;
	i_xAlarmReset		: BOOL;
END_VAR
VAR_OUTPUT
	o_eCurrentPosition 			: eValvePosition;
	o_xMagnetValve				: BOOL;
	o_xWarningPositionDown 		: BOOL; //Warning when position is down becease it not stopped the machineflow
	o_xErrorPositionUpOrUnknow	: BOOL; //Error when valve is up orunknow beceause it stopped te flow of the machine
	o_xAlarmPositionUpOrUnknow	: BOOL;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>