<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Lift" Id="{1afbe77b-3853-4511-a1b1-aafdb4f0bb3f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Lift
VAR_INPUT
	i_eState 			: eSingleState;
	i_xMoveNextLayerUp	: BOOL;
	i_xAllowedToMoveDown: BOOL;
	i_xAlarmReset		: BOOL;
	i_iServoEncoder		: INT;
	i_xLightSensor1		: BOOL; // De eerste sensor die de pallet detecteerd
	i_xLightSensor2		: BOOL; // De tweede sensor die de pallet detecteerd
	i_xPin1HallSensorIn	: BOOL;
	i_xPin1HallSensorOut: BOOL;
	i_xPin2HallSensorIn	: BOOL;
	i_xPin2HallSensorOut: BOOL;	
	i_xPin3HallSensorIn	: BOOL;
	i_xPin3HallSensorOut: BOOL;	
	i_xPin4HallSensorIn	: BOOL;
	i_xPin4HallSensorOut: BOOL;
	i_xEndSwitch		: BOOL;
	i_iDistanceSensor	: INT;
END_VAR
VAR_OUTPUT
	o_xMotor 			: BOOL;
	o_xErrorLift 		: BOOL;
	o_xAlarmLift 		: BOOL;
	
	o_xMagnetValve		: BOOL;
	o_xErrorImpaler 	: BOOL;
	o_xAlarmImpaler		: BOOL;
	
	o_xPalletInPosition	: BOOL;
	o_eLiftPosition	: eLiftposition;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>