<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_StateManager" Id="{6656736e-d2f8-4818-8e53-e866a6b4d8ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StateManager
VAR_INPUT
	i_eStateInvoerBuffer1				: eSingleState;
	i_eStateBuffer2						: eSingleState;
	i_eStateBuffer3						: eSingleState;
	i_eStateBuffer4						: eSingleState;
	i_eStateBuffer5						: eSingleState;
	i_eStateDepalletizer				: eSingleState;
	i_eStateBandDepalletizerPalletizer	: eSingleState;
	i_eStatePalletizer					: eSingleState;
	i_eStateBlikjesBand					: eSingleState;
END_VAR
VAR_OUTPUT
	o_eGeneralState	: eGeneralState;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>